### ISSUE TITLE
SSDT Patches

### ISSUE THREAD

**Issue by leocg** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#22]
Hi, i'm trying to solve a issue with my OC build for Dell G5 5590, my laptop freeze when I plug power adapter. I used your EFI folder and the problem went away, I think I have to patch my SSDTs. Can you please tell me witch tool you used to patch your SSDTs? There's a lot of stuff going on on your ACPI folder besides standard OpenCore stuff. Did you generate all of them?

Right now I have necessary files (PLUG, EC, USBX, XOSI, AWAC...) and disable dGPU. The rest you did dumping your DSDT/SSDT and patching with MacIASL? Did you get any of them in some repository I can look at?

Oh, one more thing: is there any special reason you chose FakeSMC instead of VirtualSMC? I'm asking cause OpenCore guides tell us to use VirtualSMC instead.

Thanks!

**Comment by CerteKim** [comment]
`Can you please tell me witch tool you used to patch your SSDTs?`
Nothing special, just vscode with some extension and [acpica](https://www.archlinux.org/packages/community/x86_64/acpica/) on ArchLinux.

`Did you generate all of them?`
No, but here are some ACPI Hotpatch Samples: [daliansky/P-little](https://github.com/daliansky/P-little), [daliansky/OC-little](https://github.com/daliansky/OC-little)

`The rest you did dumping your DSDT/SSDT and patching with MacIASL?`
No, just acpica.

`Did you get any of them in some repository I can look at?`
In ACPI_dump folder, I have a shell script `dump.sh` ready.

`is there any special reason you chose FakeSMC instead of VirtualSMC?`
No. A few months ago, there are some wierd issues with VirtualSMC. But now it works fine. I will update this repository soon.

Or, you can check [OCbeta](https://github.com/CerteKim/Dell-G3-3579-3779-Hackintosh-OpenCore/tree/OCbeta) branch

**Comment by leocg** [comment]
Thank you!! I'll look into them!
